server:
  port: 8081
spring:
  application:
    name: dorotech
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:dorotech;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

